---
title: "Zheln Manual 1.0.0-draft"
author: "Pavel Zhelnov"
output:
  html_notebook:
    toc: yes
    toc_depth: 3
    toc_float: yes
  word_document:
    keep_md: yes
    toc: yes
    toc_depth: 3
bibliography: zheln.bib
csl: vancouver-brackets-no-et-al.csl
---

# README

* This is a document outlining [Zheln](https://zheln.com) concept and methods to underpin its [full-scale launch](https://github.com/drzhelnov/zheln.github.io/projects/4), [methodology](https://github.com/drzhelnov/zheln.github.io/projects/2), and [funding](https://github.com/drzhelnov/zheln.github.io/projects/3).
* The Manual implements the [business plan outline](https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan) suggested by the [US Small Business Administration](https://www.sba.gov/).
* This Manual is versioned in line with [Semantic Versioning 2.0.0](https://semver.org/spec/v2.0.0.html).
* The Manual will also incorporate the [PRISMA-compliant protocol](https://github.com/drzhelnov/zheln.github.io/issues/21) for Zheln.
* The Manual is written live, and the progress can be tracked in a [dedicated kanban](https://github.com/drzhelnov/zheln.github.io/projects/4).

# Executive Summary

> Briefly tell your reader what your company is and why it will be successful. Include your mission statement, your product or service, and basic information about your company’s leadership team, employees, and location. You should also include financial information and high-level growth plans if you plan to ask for financing.

# Company Description

> Use your company description to provide detailed information about your company. Go into detail about the problems your business solves. Be specific, and list out the consumers, organization, or businesses your company plans to serve.
>
> Explain the competitive advantages that will make your business a success. Are there experts on your team? Have you found the perfect location for your store? Your company description is the place to boast about your strengths.

# Market Analysis

> You'll need a good understanding of your industry outlook and target market. Competitive research will show you what other businesses are doing and what their strengths are. In your market research, look for trends and themes. What do successful competitors do? Why does it work? Can you do it better? Now's the time to answer these questions.

# Organization and Management

> Tell your reader how your company will be structured and who will run it.
>
> Describe the legal structure of your business. State whether you have or intend to incorporate your business as a C or an S corporation, form a general or limited partnership, or if you're a sole proprietor or LLC.
>
> Use an organizational chart to lay out who's in charge of what in your company. Show how each person's unique experience will contribute to the success of your venture. Consider including resumes and CVs of key members of your team.

# Service or Product Line

> Describe what you sell or what service you offer. Explain how it benefits your customers and what the product lifecycle looks like. Share your plans for intellectual property, like copyright or patent filings. If you're doing research and development for your service or product, explain it in detail.

# Marketing and Sales

> There's no single way to approach a marketing strategy. Your strategy should evolve and change to fit your unique needs.
>
> Your goal in this section is to describe how you'll attract and retain customers. You'll also describe how a sale will actually happen. You'll refer to this section later when you make financial projections, so make sure to thoroughly describe your complete marketing and sales strategies.

# Funding Request

> If you're asking for funding, this is where you'll outline your funding requirements. Your goal is to clearly explain how much funding you’ll need over the next five years and what you'll use it for.
>
> Specify whether you want debt or equity, the terms you'd like applied, and the length of time your request will cover. Give a detailed description of how you'll use your funds. Specify if you need funds to buy equipment or materials, pay salaries, or cover specific bills until revenue increases. Always include a description of your future strategic financial plans, like paying off debt or selling your business.

# Financial Projections

> Supplement your funding request with financial projections. Your goal is to convince the reader that your business is stable and will be a financial success.
>
> If your business is already established, include income statements, balance sheets, and cash flow statements for the last three to five years. If you have other collateral you could put against a loan, make sure to list it now.
>
> Provide a prospective financial outlook for the next five years. Include forecasted income statements, balance sheets, cash flow statements, and capital expenditure budgets. For the first year, be even more specific and use quarterly — or even monthly — projections. Make sure to clearly explain your projections, and match them to your funding requests.
>
> This is a great place to use graphs and charts to tell the financial story of your business.  

# Appendix

> Use your appendix to provide supporting documents or other materials were specially requested. Common items to include are credit histories, resumes, product pictures, letters of reference, licenses, permits, or patents, legal documents, permits, and other contracts.
