---
title: "Preferred Reporting Items for Systematic reviews and Meta-Analyses extension for Scoping Reviews (PRISMA-ScR) Checklist / From: Tricco AC, Lillie E, Zarin W, O'Brien KK, Colquhoun H, Levac D, et al. PRISMA Extension for Scoping Reviews (PRISMAScR): Checklist and Explanation. Ann Intern Med. 2018;169:467–473. doi: 10.7326/M18-0850"
output:
  word_document:
    keep_md: no
    toc: false
    reference_docx: Normal.dotm
  html_notebook:
    toc: yes
    toc_depth: 3
    toc_float: yes
bibliography: RESCUER.bib
csl: gost-7-1-2003.csl
---

# TITLE

## 1 Title: Identify the report as a scoping review



# ABSTRACT

## 2 Structured summary: Provide a structured summary that includes (as applicable): background, objectives, eligibility criteria, sources of evidence, charting methods, results, and conclusions that relate to the review questions and objectives



# INTRODUCTION

## 3 Rationale: Describe the rationale for the review in the context of what is already known. Explain why the review questions/objectives lend themselves to a scoping review approach



## 4 Objectives: Provide an explicit statement of the questions and objectives being addressed with reference to their key elements (e.g., population or participants, concepts, and context) or other relevant key elements used to conceptualize the review questions and/or objectives



# METHODS

## 5 Protocol and registration: Indicate whether a review protocol exists; state if and where it can be accessed (e.g., a Web address); and if available, provide registration information, including the registration number



## 6 Eligibility criteria: Specify characteristics of the sources of evidence used as eligibility criteria (e.g., years considered, language, and publication status), and provide a rationale



## 7 Information sources*: Describe all information sources in the search (e.g., databases with dates of coverage and contact with authors to identify additional sources), as well as the date the most recent search was executed



## 8 Search: Present the full electronic search strategy for at least 1 database, including any limits used, such that it could be repeated



## 9 Selection of sources of evidence†: State the process for selecting sources of evidence (i.e., screening and eligibility) included in the scoping review



## 10 Data charting process‡: Describe the methods of charting data from the included sources of evidence (e.g., calibrated forms or forms that have been tested by the team before their use, and whether data charting was done independently or in duplicate) and any processes for obtaining and confirming data from investigators



## 11 Data items: List and define all variables for which data were sought and any assumptions and simplifications made



## 12 Critical appraisal of individual sources of evidence§: If done, provide a rationale for conducting a critical appraisal of included sources of evidence; describe the methods used and how this information was used in any data synthesis (if appropriate)



## 13 Synthesis of results: Describe the methods of handling and summarizing the data that were charted



# RESULTS

## 14 Selection of sources of evidence: Give numbers of sources of evidence screened, assessed for eligibility, and included in the review, with reasons for exclusions at each stage, ideally using a flow diagram



## 15 Characteristics of sources of evidence: For each source of evidence, present characteristics for which data were charted and provide the citations



## 16 Critical appraisal within sources of evidence: If done, present data on critical appraisal of included sources of evidence (see item 12)



## 17 Results of individual sources of evidence: For each included source of evidence, present the relevant data that were charted that relate to the review questions and objectives



## 18 Synthesis of results: Summarize and/or present the charting results as they relate to the review questions and objectives



# DISCUSSION

## 19 Summary of evidence: Summarize the main results (including an overview of concepts, themes, and types of evidence available), link to the review questions and objectives, and consider the relevance to key groups



## 20 Limitations: Discuss the limitations of the scoping review process



## 21 Conclusions: Provide a general interpretation of the results with respect to the review questions and objectives, as well as potential implications and/or next steps



# FUNDING

## 22 Funding: Describe sources of funding for the included sources of evidence, as well as sources of funding for the scoping review. Describe the role of the funders of the scoping review



# PRISMA-ScR checklist footnotes

JBI = Joanna Briggs Institute; PRISMA-ScR = Preferred Reporting Items for Systematic reviews and Meta-Analyses extension for Scoping Reviews.

* Where sources of evidence (see second footnote) are compiled from, such as bibliographic databases, social media platforms, and Web sites.

† A more inclusive/heterogeneous term used to account for the different types of evidence or data sources (e.g., quantitative and/or qualitative research, expert opinion, and policy documents) that may be eligible in a scoping review as opposed to only studies. This is not to be confused with information sources (see first footnote).

‡ The frameworks by Arksey and O’Malley (6) and Levac and colleagues (7) and the JBI guidance (4, 5) refer to the process of data extraction in a scoping review as data charting.

§ The process of systematically examining research evidence to assess its validity, results, and relevance before using it to inform a decision. This term is used for items 12 and 19 instead of "risk of bias" (which is more applicable to systematic reviews of interventions) to include and acknowledge the various sources of evidence that may be used in a scoping review (e.g., quantitative and/or qualitative research, expert opinion, and policy document).

# References
